### PR TITLE
Adding PandoraModularShowerCreation (Formally TRACS)

### PR DESCRIPTION
**Pull request by etyley**
Pull request for moving TRACS from larreco to PandoraModularShowerCreation to fix dependency issues. Specifically, moving code from larreco to larpandora to allow for dependancy on larpandoracontent which is required for the pandora sliding track fitting tool. I also took this opportunity to fix a couple of bugs, add some functionality and tidy the code base slightly:
- Store FindManyP objects in shower element holder to avoid constructing/deconstructing them many times per evern which led to performance issues in cosmic events
- Make the tools inherit fcl parameters from the module, so they do not need to be set for every tool individually
- Renamed tools to be more descriptive and coherent
- Numerous small bug fixes

In order to build you also need https://github.com/etyley/larreco-1/tree/feature/etyley_PandoraShower to remove TRACS from larreco. This has been tested in SBND and DUNE (Thanks Dom Brailsford) and has several configuration options for consistency with PandoraShowerCreation and TRACS.  

Much of the naming, specifically the fcl configurations, is very much open to discussion and any feedback is appreciated!

### CODE REVIEW

**Comment by PandoraPFA** [comment]
Thanks very much indeed @etyley - this is a very exciting development. We've assigned some reviewers and will hopefully get back to you with something intelligent to say soon! As you know, we think this is a good place to host this code, and we'll be looking to roll this out for post-patrec characterisation across the different experiments (carefully referencing you and Dom B - any other developers too?). In the first instance, we'll not try to enforce any specific style guide on this, and so will be just trying to check things for clarity and correctness. We can try playing about with a .clang-format file afterwards, if you'd like, to see how that automated style/formatting update goes! Thanks again.

**Comment by etyley** [comment]
Okay that sounds great! Bruce Howard has also agreed to help get it running in ICARUS. clang-format sounds like a good idea to me!

**Comment by PandoraPFA** [comment]
Thanks @etyley! Here's the small set of thoughts that I jotted down in our meeting:

- The big decision was to configure the fcl so that e.g. dune_pandoraShowerCreation (and equivalent for different experiments) still points to LArPandoraShowerCreation in the first instance. This means that, for all experiments, except SBND and probably ICARUS, we won't see an immediate change, and will instead opt-in to something similar to the legacy_PandoraModularShowerCreation or standard_PandoraModularShowerCreation soon.

- @absolution1 will take things forward for DUNE FD, then we'll move on to the ProtoDUNEs and uboone.

- In the longer term, but perhaps not immediately if it would mean changes for experiment-specific fcl files, we will rename the current ShowerCreation_module to SimpleShowerCreation_module, or similar/better name.

- There was some thought about whether the CMakeLists dependencies contained some unused packages, and also whether the list of header file includes was minimal (yet still comprehensive). Circular includes involving the .hh files might want some thought, and there may be something that can be factored out into a third header file.

- There was some discussion, probably for the longer term about reviewing the -999(99) values, perhaps setting up some kind of enumerated constants to keep these, and their future usage under tight control. Then there's the choice of the value used. Could consider using e.g. -std::numeric_limits<float>::max() (which works because there is a bit for the sign on most platforms) in future. (And look out for any associated floating point equality checks, which may be more in downstream analysis code.)

- There were a few variables in the two algorithms that were created but not given default values at the point of creation - any initial value should help there. E.g. line 77 onward of LArPandoraCheatingShowerAlg.

- Should remove any changes to ups/product_deps from the PR and leave that to the LArSoft team.

- In longer term, could consider adding full doxygen information to function and variable definitions in headers.

Thanks again!

**Comment by PandoraPFA** [comment]
Hi @etyley,

I spotted your most recent commits - thanks. Please continue as needed and as soon as you're nominally done (you might be ready now!), then please just comment here. Then we'll take this branch, rebase it against the tip of the develop branch, remove the ups/product_deps conflict (should usually be no changes to this file, but new eigen dependency may require an extra line) and merge into new branch of this remote repository: e.g. `feature/PandoraModularShowerCreation`.

Any CI tests you'd like to run (@absolution1 might have suggestions?) can be triggered off this branch of this repository. Then, when happy, you can submit a pull request from `PandoraPFA/larpandora/feature/PandoraModularShowerCreation` -> `LArSoft/larpandora/develop`

Thanks again, and please let me know if any of the above need clarifying (Slack chat also works for details, especially if we run into any fiddly issues rebasing or with the ups/product_deps file).

John

**Comment by etyley** [comment]
Hi John,

I am just doing some final tests to make sure that the changes did not break anything. 

Just to clarify, do you want me to fix the ups/product_deps and rebase before the branch is merged, or will you do it afterwards?

**Comment by PandoraPFA** [comment]
Hi Ed,

We usually completely leave this file, ups/product_deps, to the SciSoft team. But that's because they are responsible for setting the package version numbers, and I think these need to be incremented just before, or during, the release building.

In this case, though, we're also adding the eigen dependency, so we'd ultimately like ups to check that the right version of eigen is present before an attempt is made to build larpandora.

So my suggestion is to do one of two things:
- Completely remove all changes to this file from the final branch (which will be rebased against develop, so there will then be no diff in this file) and make it clear via the PR to LArSoft and maybe an e-mail that the eigen line should be included.

or

- Completely remove all changes to this file from the final branch, except for the one line specifying eigen v3_3_5, e.g. [here's](https://github.com/PandoraPFA/LArContent/blob/master/ups/product_deps#L15) the equivalent line from larpandoracontent

Hope that helps. Did you have a play around with the .clang-format, btw?

Thanks again!

John

**Comment by etyley** [comment]
Hi John,

Okay that sounds great, I will remove the changes and email the SciSoft team to let them know of the upcoming pull request there and the eigen requirement. 

I have started having a play with clang-format, but was waiting until everything else was finalised before applying it. 
I had a few questions about specific details that we should discuss over slack.

**Comment by PandoraPFA** [comment]
Merged into feature branch: `feature/PandoraModularShowerReconstruction` - thanks!

**Pull request closed without merging**
