### PR TITLE
Added a check for when SimChannels object is available, but empty

### PR DESCRIPTION
**Pull request by loressa**
should happen only in empty BNB only events (i.e. DUNE FD), or customised MC productions producing somehow empty events

### CODE REVIEW

**Comment by PandoraPFA** [comment]
Hi Lorena,

This looks good to me, reading through your latest diffs (you even fixed some whitespace and added some missing Doxygen commenting!), so the next step hangs on the test results.

My suggestion is that you satisfy yourself about the test results and then you can click to merge this, before cherry-picking the commit into a new branch prepared for Redmine (with its non-rewritten repository history!). After the LArSoft release, we can resync GitHub and Redmine and make a mental note to get the Redmine history fixed once and for all sometime.

With all the usual caveats about testing changes one at a time, it might be more efficient to include both this, and the LArContent change in your testing of e.g. CI events. Both changes have been crawled over by multiple people now.

Thanks,

John

**Comment by loressa** [comment]
Hello,

Thanks for the comments. I have now updated the files following them and they are available in the commit https://github.com/PandoraPFA/LArPandora/pull/12/commits/ff959d04e02d06cbd16a55f3330d314fdd785dc1
Also in the redmine feature branch escudero_SimChannelsValid https://cdcvs.fnal.gov/redmine/projects/larpandora/repository/show/larpandora?utf8=✓&rev=feature%2Fescudero_SimChannelsValid
About to start testing that feature branch 

Thanks,
Lorena

**Comment by PandoraPFA** [comment]
Presumably this was merged on Redmine and this PR can now be closed?

**Comment by loressa** [comment]
yes, thats correct:
https://github.com/PandoraPFA/LArPandora/commit/e39e84a952b7fc182595ba7a1a66d2b0b8cc7488

**Comment by PandoraPFA** [comment]
Thanks!

**Pull request closed without merging**
