### PR TITLE
Bugfix/etyley_dEdx

### LINKED ISSUE #8: Bug in fcl param names in the Bayes dE/dx tool in Pandora Modular Shower Creation
In the Bayes dE/dx tool in the Pandora Modular Shower Creation, there is a slight bug in the fcl parameter names.

I was using version v09_01_00 of larpandora for v09_03_00 of larsoft.

The parameters used to be called ProbDiff and ProbDiffSeed, but in the Modular Shower's showertools.fcl these have been renamed as ProbSeedCut and ProbPointCut. (Forget which maps to which offhand).

However, in the Module itself, these names were not changed:

fProbSeedCut(pset.get<float>("ProbDiff")),
fProbPointCut(pset.get<float>("ProbDiffSeed")),

which leads to the module complaining. This is of course easily worked around in one's job fcl, but in any case probably the committed versions should be fixed!

### PR DESCRIPTION
**Pull request by etyley**
This PR contains fixes for 2 separate bugs in the dEdx calculation tools in PandoraModularShowerCreation:

BayesianTruncationdEdx: 
- Fix mismatched fcl parameter names (Fixes #8)
- Removed reference to SBND specific prior file that was giving an error for not being found in ICARUS. 

TrajPointdEdx:
- Fix issue with initialisation of max_hits when calculating the best plane which lead to planes with 0 hits being taken as the best plane. Now require at least one plane to have at least one hit or return an error, the previously intended behaviour hopefully implemented correctly now
- Added additional debug output for ease of future debugging

This has been tested in SBND (myself), DUNE (@absolution1) and ICARUS (@brucehoward-physics) and no changes to output are expected with default configurations.

### CODE REVIEW

**Review by absolution1 — APPROVED** [review]
Minimal changes with extra printout; seems good to me!
I'm not sure if anyone else will want to comment on the content but I'll slap my approval on now.

**Review by AndyChappell — APPROVED** [review]
Changes all look logical to me

**Comment by etyley** [comment]
I have tested this with LArSoft v09_06_00 and can confirm the updates that were merged in this version have no effect on this fix. I have no more checks to do before this is merged now.

**Comment by AndyChappell** [comment]
> I have tested this with LArSoft v09_06_00 and can confirm the updates that were merged in this version have no effect on this fix. I have no more checks to do before this is merged now.

Thanks Ed, I've merged the changes, so please feel free to issue a pull request to LArSoft.

**Pull request merged**
